name: Generate PIO header

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          npm install --save pioasm;
          
          node -e '
          
          //import { PIOAssembler } from "pioasm";
          var PIOAssembler = import("pioasm").PIOAssembler;
          var fs = require("fs");

          const source = fs.readFileSync(
            "src/hx711_noblock.pio",
            "utf8");

          const pioasm = new PIOAssembler();
          pioasm.assemble(source).then(result => {
            console.log(result.output);
          })
          ';